
## OAuth2ClientConfig에서 Bean방식으로 ClientRegistration 구성시 주석처리
#spring:
#  security:
#    oauth2:
#      client:
#
#        registration: # Client Info
#          keycloak:
#            authorizationGrantType: authorization_code
#            clientId: oauth2-client-app     # 필수값
#            clientName: oauth2-client-app   # 필수값
#            clientSecret: oTzOtDvPQr7R2yxtJKOHN4gB3FNTKpfw
#            redirectUri: http://localhost:8080/login/oauth2/code/keycloak # 필수값
#            clientAuthenticationMethod: client_secret_basic
#            scope: openid,email,profile
#
#        provider: # Provider Info (Authorization Server Endpoint)
#          keycloak:
#            authorizationUri: http://localhost:8081/realms/oauth2/protocol/openid-connect/auth
#            issuerUri: http://localhost:8081/realms/oauth2  # 필수값
#            jwkSetUri: http://localhost:8081/realms/oauth2/protocol/openid-connect/certs
#            tokenUri: http://localhost:8081/realms/oauth2/protocol/openid-connect/token
#            userInfoUri: http://localhost:8081/realms/oauth2/protocol/openid-connect/userinfo
#            userNameAttribute: preferred_username